### PR TITLE
Added startOfInput parser

### PR DESCRIPTION
**Pull request by anoopmd**
## descriptive title

- [ ] This PR  only introduces changes to documentation.
  - Please include a summary of changes and an explanation
- [X] This PR adds new functionality
  - [ ] Is there a related issue?
    - Please note the related issue below, and how this PR relates to the issue if appropriate
  - [X] Does the code style reasonably match the existing code?
  - [X] Are the changes tested (using the existing format, as far as is possible?)
  - [X] Are the changes documented in the readme with a suitable example?
  - [X] Is the table of contents updated?
- [ ] This PR introduces some other kind of change
  - Please explain the change below

### CODE REVIEW

**Comment by anoopmd** [comment]
For some reason, when I commit, the pre commit hooks are auto prettifying things which is make the diff really huge. Any suggestions to avoid this @francisrstokes ?

**Comment by anoopmd** [comment]
My changes are pretty minimal
index.mjs
```javascript
//           startOfInput :: Parser e String s
export const startOfInput = new Parser(function startOfInput$state(state) {
  if (state.isError) return state;
  const { index } = state;
  if (index > 0) {
    return updateError(
      state,
      `ParseError 'startOfInput' (position ${index}): Expected start of input'`,
    );
  }

  return state;
});
```

test.js
```javascript
test('startOfInput', () => {
  const mustBeginWithHeading = sequenceOf([startOfInput, str('# ')]);
  const parser = between(mustBeginWithHeading)(endOfInput)(
    everyCharUntil(endOfInput),
  );
  expectedSuccessTest(parser, 'Heading', '# Heading')();
  expectedFailTest(parser, ' # Heading')();
});
```

@francisrstokes I'd be happy to re-raise a PR if you could guide on how to fix the prettier auto formatting stuff.

**Comment by francisrstokes** [comment]
Hey @anoopmd - I see. I was kind of on the fence about strictly enforcing a style through pre-commit auto linting, but I think now I'm pretty settled on it being unnecessary.

I've removed it now on master, so if you rebase (or even just copy paste your changes and open a new PR), I'll merge. Thanks for taking the time to add this feature!

**Comment by anoopmd** [comment]
Thanks @francisrstokes I'll raise a new PR

**Pull request closed without merging**
