### PR TITLE
Fix some issues with README.md

### PR DESCRIPTION
**Pull request by IMax153**
This PR fixes a few small issues in the README file. 

I also noticed a small issue with the links to the individual parser methods  in the README (i.e. `.run`, `.fork`, etc.). The links will work locally on my machine, but for some reason do not work when I view the README on GitHub. I am not sure if it really *needs* to be fixed, but maybe removing the leading `.` would give the links the correct behavior? Not sure though.

### CODE REVIEW

**Comment by francisrstokes** [comment]
Hey Max,

Nice, thank you.

>I also noticed a small issue with the links to the individual parser methods

I've noticed that too, and I'm not sure either. However it should be pretty easy to verify!

If you commit the changed links in your PR, you can view the branch in github (on the main page, select your branch in the dropdown just below the number of commits) and see if the links work there. If not, you can always ditch the commit.

**Comment by IMax153** [comment]
Thanks Francis, I am relatively new to open source and have been learning by observing thus far, so I greatly appreciate advice such as this!

I removed the leading `.` and that seemed to fix the linking behavior.

**Comment by francisrstokes** [comment]
Awesome, great stuff!

**Comment by francisrstokes** [comment]
🎉

**Pull request merged**
